import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import contactsRouter from "./contacts";
import interactionsRouter from "./interactions";
import ingestRouter from "./ingest";
import chatRouter from "./chat";
import agentRouter from "./agent";
import notificationsRouter from "./notifications";
import remindersRouter from "./reminders";
import hubRouter from "./hub";
import dashboardRouter from "./dashboard";
import telegramRouter from "./telegram";
import discordBotRouter from "./discord-bot";
import devSeedRouter from "./dev-seed";
import storageRouter from "./storage";
import friendsRouter from "./friends";
import followupsRouter from "./followups";
import priorityRouter from "./priority";
import calendarRouter from "./calendar";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(contactsRouter);
router.use(interactionsRouter);
router.use(ingestRouter);
router.use(chatRouter);
router.use(agentRouter);
router.use(notificationsRouter);
router.use(remindersRouter);
router.use(hubRouter);
router.use(dashboardRouter);
router.use(telegramRouter);
router.use(discordBotRouter);
router.use(devSeedRouter);
router.use(storageRouter);
router.use(friendsRouter);
router.use(followupsRouter);
router.use(priorityRouter);
router.use(calendarRouter);

export default router;
